/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import minas.de.oro.Terreno;

/**
 *
 * @author cesar
 */
public class Simulacion extends javax.swing.JFrame {

    /**
     * Creates new form Simulación
     */
    public Simulacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        territorioPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout territorioPanelLayout = new javax.swing.GroupLayout(territorioPanel);
        territorioPanel.setLayout(territorioPanelLayout);
        territorioPanelLayout.setHorizontalGroup(
            territorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );
        territorioPanelLayout.setVerticalGroup(
            territorioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(territorioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(territorioPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel territorioPanel;
    // End of variables declaration//GEN-END:variables
    
    
    public void colorearTerreno(Terreno terreno) {
        Color grisClaro = new Color(209, 139, 71);
        Color grisOscuro = new Color(255, 206, 158);
        for (int i = 0; i < terreno.getAncho()*terreno.getLargo(); i++) {
            JPanel square = new JPanel(new BorderLayout());
            territorioPanel.add(square);

            int row = (i / terreno.getAncho()) % 2;
            if (row == 0) {
                square.setBackground(i % 2 == 0 ? grisClaro : grisOscuro);
            } else {
                square.setBackground(i % 2 == 0 ? grisOscuro : grisClaro);
            }
        }
    }
    
    public void llenarTerreno(Terreno terreno) {
        territorioPanel.setLayout(new java.awt.GridLayout(terreno.getLargo(), terreno.getAncho()));
        territorioPanel.removeAll();
        colorearTerreno(terreno);
    }
}
